### ISSUE TITLE
Memory chunk

### ISSUE THREAD

**Issue by dbof10** [nntuyen/mkloader#2]
After having watched memory allocation, I noticed that lots of `Float`, `Integer` object created during `onAnimationUpdate` method.

**Comment by nntuyen** [comment]
Thanks @dbof10, I'm working on it.

**Comment by dbof10** [comment]
Any update?

**Comment by nntuyen** [comment]
Released version 1.2.0 that fixes memory leak.

**Comment by dbof10** [comment]
After going through your new commit, it didn't solve my problem.

**Comment by nntuyen** [comment]
Could you please provide some screenshots or something to indicate the issue?
