### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by ezubkov** [nntuyen/mkloader#7]
Hello, i've found a little mistake which makes memory leaks. In each implementation of LoaderView you use **invalidateListener** in _infinity_ ValueAnimator and it holds a context (yep, activity).

Easy solution:
Add to MKLoader view:
`   protected void onDetachedFromWindow() {
          super.onDetachedFromWindow();
          loaderView.setInvalidateListener(null);
    }
`

and in each ValueAnimator check for `invalidateListener == null` and stop animations

**Comment by nntuyen** [comment]
Hi @ezubkov, 
This issue was fixed. You can check [issue # 5](https://github.com/nntuyen/mkloader/issues/5) for more details,
