### ISSUE TITLE
Please remove allowBackup from library's manifest file.

### ISSUE THREAD

**Issue by dbychkov** [nntuyen/mkloader#8]
Please remove allowBackup from library's manifest file.It conflicts with the main app's manifest.

**Comment by nntuyen** [comment]
@dbychkov thanks. It will be fixed with next release.

**Comment by nntuyen** [comment]
@dbychkov v1.3.0 is released that fix the issue

**Comment by nntuyen** [comment]
@dbychkov the issue is fixed in v1.3.0

**Comment by dbychkov** [comment]
@nntuyen Thanks!
