### ISSUE TITLE
Animation stops if loader is inside a recycler view item

### ISSUE THREAD

**Issue by bafitor** [nntuyen/mkloader#9]
Hi,

I noticed that if you put the MKLoader inside a recycler view item, when the view holder is recycled the animation is stopped.

Can you look at the issue? 

Thanks

**Comment by nntuyen** [comment]
@bafitor could you post your code?

**Comment by bafitor** [comment]
Sure, check this repo:

https://github.com/bafitor/MKLoaderTest

**Comment by nntuyen** [comment]
@bafitor the animation's stopped because child view is detached and do nothing when it attached again. It's mkloader issue and I'll try to fix it by the end of this week.

**Comment by nntuyen** [comment]
@bafitor fixed on 1.4.0, check [ListTestActivity.java](https://github.com/nntuyen/mkloader/blob/master/app/src/main/java/com/tuyenmonkey/sample/ListTestActivity.java) for example.
